apiVersion: triggers.tekton.dev/v1beta1 
kind: TriggerTemplate 
metadata:
  name: quarkus-hello-world
spec:
  params: 
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates: 
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      annotations:
        chains.tekton.dev/signed: 'true'
      name: deploy-$(tt.params.git-repo-name)-$(uid)
      finalizers:
        - chains.tekton.dev/pipelinerun
      labels:
        tekton.dev/pipeline: deploy-pipeline
    spec:
      pipelineRef:
        name: deploy-pipeline
      taskRunTemplate:
        serviceAccountName: pipeline
      timeouts:
        pipeline: 1h0m0s
      workspaces:
        - name: deploy
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: gp3-csi
              volumeMode: Filesystem
            status: {}
---
apiVersion: triggers.tekton.dev/v1beta1 
kind: Trigger 
metadata:
  name: quarkus-hello-world 
spec:
  interceptors:
    - ref:
        name: "github" 
      params: 
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: github-push 
  template: 
      ref: quarkus-hello-world
---
apiVersion: triggers.tekton.dev/v1beta1 
kind: EventListener 
metadata:
  name: quarkus-hello-world 
spec:
  triggers:
    - triggerRef: quarkus-hello-world 
